using System.Drawing;
using System.Windows.Forms;
namespace Вычислятор_Blitz
{
	partial class MainWndw
	{
		System.ComponentModel.IContainer components = null;
		GroupBox Група_0;
		PictureBox IconЗолото_0;
		TextBox GoldBox_0;
		PictureBox IconСтрелка_0;
		PictureBox IconСеребро_0;
		Label СереброLabel_0;
		GroupBox Група_1;
		CheckBox АкцияChecker_0;
		Label ОпытLabel_0;
		PictureBox IconОпыт_0;
		PictureBox IconСтрелка_1;
		PictureBox IconЗолото_1;
		TextBox GoldBox_1;
		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null)
				components.Dispose();
			base.Dispose(disposing);
		}
		void InitializeComponent()
		{
			Група_0 = new GroupBox();
			СереброLabel_0 = new Label();
			IconСеребро_0 = new PictureBox();
			IconСтрелка_0 = new PictureBox();
			IconЗолото_0 = new PictureBox();
			GoldBox_0 = new TextBox();
			Група_1 = new GroupBox();
			АкцияChecker_0 = new CheckBox();
			ОпытLabel_0 = new Label();
			IconОпыт_0 = new PictureBox();
			IconСтрелка_1 = new PictureBox();
			IconЗолото_1 = new PictureBox();
			GoldBox_1 = new TextBox();
			Група_0.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(IconСеребро_0)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(IconСтрелка_0)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(IconЗолото_0)).BeginInit();
			Група_1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(IconОпыт_0)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(IconСтрелка_1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(IconЗолото_1)).BeginInit();
			SuspendLayout();
			Група_0.Controls.Add(СереброLabel_0);
			Група_0.Controls.Add(IconСеребро_0);
			Група_0.Controls.Add(IconСтрелка_0);
			Група_0.Controls.Add(IconЗолото_0);
			Група_0.Controls.Add(GoldBox_0);
			Група_0.Font = new Font("Arial", 8F);
			Група_0.Location = new Point(4, 2);
			Група_0.Margin = new Padding(0);
			Група_0.Name = "Група_0";
			Група_0.Padding = new Padding(2);
			Група_0.Size = new Size(304, 47);
			Група_0.TabIndex = 0;
			Група_0.TabStop = false;
			Група_0.Text = "Переобразователь золота в серебро";
			Група_0.UseCompatibleTextRendering = true;
			СереброLabel_0.FlatStyle = FlatStyle.Flat;
			СереброLabel_0.Font = new Font("Tahoma", 7.8F, FontStyle.Bold, GraphicsUnit.Point, ((byte)(204)));
			СереброLabel_0.Location = new Point(161, 20);
			СереброLabel_0.Name = "СереброLabel_0";
			СереброLabel_0.Size = new Size(141, 22);
			СереброLabel_0.TabIndex = 3;
			СереброLabel_0.Text = "Тут будет серебро";
			СереброLabel_0.TextAlign = ContentAlignment.MiddleLeft;
			СереброLabel_0.UseCompatibleTextRendering = true;
			IconСеребро_0.BackgroundImage = Ресурсы.Серебро;
			IconСеребро_0.BackgroundImageLayout = ImageLayout.Zoom;
			IconСеребро_0.Location = new Point(134, 20);
			IconСеребро_0.Name = "IconСеребро_0";
			IconСеребро_0.Size = new Size(21, 22);
			IconСеребро_0.TabIndex = 2;
			IconСеребро_0.TabStop = false;
			IconСтрелка_0.BackgroundImage = Ресурсы.Стрелочка;
			IconСтрелка_0.BackgroundImageLayout = ImageLayout.Zoom;
			IconСтрелка_0.Location = new Point(112, 20);
			IconСтрелка_0.Name = "IconСтрелка_0";
			IconСтрелка_0.Size = new Size(16, 22);
			IconСтрелка_0.TabIndex = 1;
			IconСтрелка_0.TabStop = false;
			IconЗолото_0.BackgroundImage = Ресурсы.Золото;
			IconЗолото_0.BackgroundImageLayout = ImageLayout.Zoom;
			IconЗолото_0.Location = new Point(4, 20);
			IconЗолото_0.Name = "IconЗолото_0";
			IconЗолото_0.Size = new Size(21, 22);
			IconЗолото_0.TabIndex = 0;
			IconЗолото_0.TabStop = false;
			GoldBox_0.Font = new Font("Arial", 7.8F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(204)));
			GoldBox_0.Location = new Point(31, 20);
			GoldBox_0.MaxLength = 9;
			GoldBox_0.Name = "GoldBox_0";
			GoldBox_0.ShortcutsEnabled = false;
			GoldBox_0.Size = new Size(75, 22);
			GoldBox_0.TabIndex = 0;
			GoldBox_0.TextAlign = HorizontalAlignment.Center;
			GoldBox_0.WordWrap = false;
			Група_1.Controls.Add(АкцияChecker_0);
			Група_1.Controls.Add(ОпытLabel_0);
			Група_1.Controls.Add(IconОпыт_0);
			Група_1.Controls.Add(IconСтрелка_1);
			Група_1.Controls.Add(IconЗолото_1);
			Група_1.Controls.Add(GoldBox_1);
			Група_1.Font = new Font("Arial", 8F);
			Група_1.Location = new Point(4, 48);
			Група_1.Margin = new Padding(0);
			Група_1.Name = "Група_1";
			Група_1.Padding = new Padding(2);
			Група_1.Size = new Size(304, 68);
			Група_1.TabIndex = 4;
			Група_1.TabStop = false;
			Група_1.Text = "Переобразователь золота в опыт";
			Група_1.UseCompatibleTextRendering = true;
			АкцияChecker_0.Font = new Font("Tahoma", 9F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(204)));
			АкцияChecker_0.Location = new Point(4, 45);
			АкцияChecker_0.Margin = new Padding(0);
			АкцияChecker_0.Name = "АкцияChecker_0";
			АкцияChecker_0.Size = new Size(298, 20);
			АкцияChecker_0.TabIndex = 4;
			АкцияChecker_0.Text = "По акции";
			АкцияChecker_0.UseCompatibleTextRendering = true;
			ОпытLabel_0.FlatStyle = FlatStyle.Flat;
			ОпытLabel_0.Font = new Font("Tahoma", 7.8F, FontStyle.Bold);
			ОпытLabel_0.Location = new Point(161, 20);
			ОпытLabel_0.Name = "ОпытLabel_0";
			ОпытLabel_0.Size = new Size(141, 22);
			ОпытLabel_0.TabIndex = 3;
			ОпытLabel_0.Text = "Тут будет опыт";
			ОпытLabel_0.TextAlign = ContentAlignment.MiddleLeft;
			ОпытLabel_0.UseCompatibleTextRendering = true;
			IconОпыт_0.BackgroundImage = Ресурсы.Опыт;
			IconОпыт_0.BackgroundImageLayout = ImageLayout.Zoom;
			IconОпыт_0.Location = new Point(134, 20);
			IconОпыт_0.Name = "IconОпыт_0";
			IconОпыт_0.Size = new Size(21, 22);
			IconОпыт_0.TabIndex = 2;
			IconОпыт_0.TabStop = false;
			IconСтрелка_1.BackgroundImage = Ресурсы.Стрелочка;
			IconСтрелка_1.BackgroundImageLayout = ImageLayout.Zoom;
			IconСтрелка_1.Location = new Point(112, 20);
			IconСтрелка_1.Name = "IconСтрелка_1";
			IconСтрелка_1.Size = new Size(16, 22);
			IconСтрелка_1.TabIndex = 1;
			IconСтрелка_1.TabStop = false;
			IconЗолото_1.BackgroundImage = Ресурсы.Золото;
			IconЗолото_1.BackgroundImageLayout = ImageLayout.Zoom;
			IconЗолото_1.Location = new Point(4, 20);
			IconЗолото_1.Name = "IconЗолото_1";
			IconЗолото_1.Size = new Size(21, 22);
			IconЗолото_1.TabIndex = 0;
			IconЗолото_1.TabStop = false;
			GoldBox_1.Font = new Font("Arial", 7.8F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(204)));
			GoldBox_1.Location = new Point(31, 20);
			GoldBox_1.MaxLength = 9;
			GoldBox_1.Name = "GoldBox_1";
			GoldBox_1.ShortcutsEnabled = false;
			GoldBox_1.Size = new Size(75, 22);
			GoldBox_1.TabIndex = 0;
			GoldBox_1.TextAlign = HorizontalAlignment.Center;
			GoldBox_1.WordWrap = false;
			AutoScaleMode = AutoScaleMode.None;
			BackColor = Color.White;
			ClientSize = new Size(312, 119);
			Controls.Add(Група_1);
			Controls.Add(Група_0);
			DoubleBuffered = true;
			Font = new Font("Arial", 7.8F);
			ForeColor = Color.Black;
			FormBorderStyle = FormBorderStyle.FixedSingle;
			Icon = Ресурсы.Иконка;
			MaximizeBox = false;
			Name = "MainWndw";
			Opacity = 0D;
			StartPosition = FormStartPosition.CenterScreen;
			Text = "Вычислятор Blitz";
			TopMost = true;
			Група_0.ResumeLayout(false);
			Група_0.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(IconСеребро_0)).EndInit();
			((System.ComponentModel.ISupportInitialize)(IconСтрелка_0)).EndInit();
			((System.ComponentModel.ISupportInitialize)(IconЗолото_0)).EndInit();
			Група_1.ResumeLayout(false);
			Група_1.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(IconОпыт_0)).EndInit();
			((System.ComponentModel.ISupportInitialize)(IconСтрелка_1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(IconЗолото_1)).EndInit();
			ResumeLayout(false);
		}
	}
}