using System.Drawing;
using System.Windows.Forms;
namespace Вычислятор_Blitz
{
	partial class MainWndw
	{
		System.ComponentModel.IContainer components = null;
		GroupBox Група_0;
		PictureBox ИзображениеЗолота_0;
		TextBox GoldBox_0;
		PictureBox ИзображениеСтрелочки_0;
		PictureBox ИзображениеСеребра_0;
		Label СереброLabel_0;
		GroupBox Група_1;
		CheckBox АкцияChecker_0;
		Label ОпытLabel_0;
		PictureBox ИзображениеОпыта_0;
		PictureBox ИзображениеСтрелочки_1;
		PictureBox ИзображениеЗолота_1;
		TextBox GoldBox_1;
		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null)
				components.Dispose();
			base.Dispose(disposing);
		}
		void InitializeComponent()
		{
			Група_0 = new GroupBox();
			СереброLabel_0 = new Label();
			ИзображениеСеребра_0 = new PictureBox();
			ИзображениеСтрелочки_0 = new PictureBox();
			ИзображениеЗолота_0 = new PictureBox();
			GoldBox_0 = new TextBox();
			Група_1 = new GroupBox();
			АкцияChecker_0 = new CheckBox();
			ОпытLabel_0 = new Label();
			ИзображениеОпыта_0 = new PictureBox();
			ИзображениеСтрелочки_1 = new PictureBox();
			ИзображениеЗолота_1 = new PictureBox();
			GoldBox_1 = new TextBox();
			Група_0.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(ИзображениеСеребра_0)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(ИзображениеСтрелочки_0)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(ИзображениеЗолота_0)).BeginInit();
			Група_1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(ИзображениеОпыта_0)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(ИзображениеСтрелочки_1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(ИзображениеЗолота_1)).BeginInit();
			SuspendLayout();
			Група_0.Controls.Add(СереброLabel_0);
			Група_0.Controls.Add(ИзображениеСеребра_0);
			Група_0.Controls.Add(ИзображениеСтрелочки_0);
			Група_0.Controls.Add(ИзображениеЗолота_0);
			Група_0.Controls.Add(GoldBox_0);
			Група_0.Font = new Font("Arial", 8F);
			Група_0.Location = new Point(4, 2);
			Група_0.Margin = new Padding(0);
			Група_0.Name = "Група_0";
			Група_0.Padding = new Padding(2);
			Група_0.Size = new Size(304, 47);
			Група_0.TabIndex = 0;
			Група_0.TabStop = false;
			Група_0.Text = "Переобразователь золота в серебро";
			Група_0.UseCompatibleTextRendering = true;
			СереброLabel_0.FlatStyle = FlatStyle.Flat;
			СереброLabel_0.Font = new Font("Tahoma", 7.8F, FontStyle.Bold, GraphicsUnit.Point, ((byte)(204)));
			СереброLabel_0.Location = new Point(161, 20);
			СереброLabel_0.Name = "СереброLabel_0";
			СереброLabel_0.Size = new Size(141, 22);
			СереброLabel_0.TabIndex = 3;
			СереброLabel_0.Text = "Тут будет серебро";
			СереброLabel_0.TextAlign = ContentAlignment.MiddleLeft;
			СереброLabel_0.UseCompatibleTextRendering = true;
			ИзображениеСеребра_0.BackgroundImage = Ресурсы.Серебро;
			ИзображениеСеребра_0.BackgroundImageLayout = ImageLayout.Zoom;
			ИзображениеСеребра_0.Location = new Point(134, 20);
			ИзображениеСеребра_0.Name = "ИзображениеСеребра_0";
			ИзображениеСеребра_0.Size = new Size(21, 22);
			ИзображениеСеребра_0.TabIndex = 2;
			ИзображениеСеребра_0.TabStop = false;
			ИзображениеСтрелочки_0.BackgroundImage = Ресурсы.Стрелочка;
			ИзображениеСтрелочки_0.BackgroundImageLayout = ImageLayout.Zoom;
			ИзображениеСтрелочки_0.Location = new Point(112, 20);
			ИзображениеСтрелочки_0.Name = "ИзображениеСтрелочки_0";
			ИзображениеСтрелочки_0.Size = new Size(16, 22);
			ИзображениеСтрелочки_0.TabIndex = 1;
			ИзображениеСтрелочки_0.TabStop = false;
			ИзображениеЗолота_0.BackgroundImage = Ресурсы.Золото;
			ИзображениеЗолота_0.BackgroundImageLayout = ImageLayout.Zoom;
			ИзображениеЗолота_0.Location = new Point(4, 20);
			ИзображениеЗолота_0.Name = "ИзображениеЗолота_0";
			ИзображениеЗолота_0.Size = new Size(21, 22);
			ИзображениеЗолота_0.TabIndex = 0;
			ИзображениеЗолота_0.TabStop = false;
			GoldBox_0.Font = new Font("Arial", 7.8F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(204)));
			GoldBox_0.Location = new Point(31, 20);
			GoldBox_0.MaxLength = 9;
			GoldBox_0.Name = "GoldBox_0";
			GoldBox_0.ShortcutsEnabled = false;
			GoldBox_0.Size = new Size(75, 22);
			GoldBox_0.TabIndex = 0;
			GoldBox_0.TextAlign = HorizontalAlignment.Center;
			GoldBox_0.WordWrap = false;
			Група_1.Controls.Add(АкцияChecker_0);
			Група_1.Controls.Add(ОпытLabel_0);
			Група_1.Controls.Add(ИзображениеОпыта_0);
			Група_1.Controls.Add(ИзображениеСтрелочки_1);
			Група_1.Controls.Add(ИзображениеЗолота_1);
			Група_1.Controls.Add(GoldBox_1);
			Група_1.Font = new Font("Arial", 8F);
			Група_1.Location = new Point(4, 48);
			Група_1.Margin = new Padding(0);
			Група_1.Name = "Група_1";
			Група_1.Padding = new Padding(2);
			Група_1.Size = new Size(304, 68);
			Група_1.TabIndex = 4;
			Група_1.TabStop = false;
			Група_1.Text = "Переобразователь золота в опыт";
			Група_1.UseCompatibleTextRendering = true;
			АкцияChecker_0.Font = new Font("Tahoma", 9F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(204)));
			АкцияChecker_0.Location = new Point(4, 45);
			АкцияChecker_0.Margin = new Padding(0);
			АкцияChecker_0.Name = "АкцияChecker_0";
			АкцияChecker_0.Size = new Size(298, 20);
			АкцияChecker_0.TabIndex = 4;
			АкцияChecker_0.Text = "По акции";
			АкцияChecker_0.UseCompatibleTextRendering = true;
			ОпытLabel_0.FlatStyle = FlatStyle.Flat;
			ОпытLabel_0.Font = new Font("Tahoma", 7.8F, FontStyle.Bold);
			ОпытLabel_0.Location = new Point(161, 20);
			ОпытLabel_0.Name = "ОпытLabel_0";
			ОпытLabel_0.Size = new Size(141, 22);
			ОпытLabel_0.TabIndex = 3;
			ОпытLabel_0.Text = "Тут будет опыт";
			ОпытLabel_0.TextAlign = ContentAlignment.MiddleLeft;
			ОпытLabel_0.UseCompatibleTextRendering = true;
			ИзображениеОпыта_0.BackgroundImage = Ресурсы.Опыт;
			ИзображениеОпыта_0.BackgroundImageLayout = ImageLayout.Zoom;
			ИзображениеОпыта_0.Location = new Point(134, 20);
			ИзображениеОпыта_0.Name = "ИзображениеОпыта_0";
			ИзображениеОпыта_0.Size = new Size(21, 22);
			ИзображениеОпыта_0.TabIndex = 2;
			ИзображениеОпыта_0.TabStop = false;
			ИзображениеСтрелочки_1.BackgroundImage = Ресурсы.Стрелочка;
			ИзображениеСтрелочки_1.BackgroundImageLayout = ImageLayout.Zoom;
			ИзображениеСтрелочки_1.Location = new Point(112, 20);
			ИзображениеСтрелочки_1.Name = "ИзображениеСтрелочки_1";
			ИзображениеСтрелочки_1.Size = new Size(16, 22);
			ИзображениеСтрелочки_1.TabIndex = 1;
			ИзображениеСтрелочки_1.TabStop = false;
			ИзображениеЗолота_1.BackgroundImage = Ресурсы.Золото;
			ИзображениеЗолота_1.BackgroundImageLayout = ImageLayout.Zoom;
			ИзображениеЗолота_1.Location = new Point(4, 20);
			ИзображениеЗолота_1.Name = "ИзображениеЗолота_1";
			ИзображениеЗолота_1.Size = new Size(21, 22);
			ИзображениеЗолота_1.TabIndex = 0;
			ИзображениеЗолота_1.TabStop = false;
			GoldBox_1.Font = new Font("Arial", 7.8F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(204)));
			GoldBox_1.Location = new Point(31, 20);
			GoldBox_1.MaxLength = 9;
			GoldBox_1.Name = "GoldBox_1";
			GoldBox_1.ShortcutsEnabled = false;
			GoldBox_1.Size = new Size(75, 22);
			GoldBox_1.TabIndex = 0;
			GoldBox_1.TextAlign = HorizontalAlignment.Center;
			GoldBox_1.WordWrap = false;
			AutoScaleMode = AutoScaleMode.None;
			BackColor = Color.White;
			ClientSize = new Size(312, 119);
			Controls.Add(Група_1);
			Controls.Add(Група_0);
			DoubleBuffered = true;
			Font = new Font("Arial", 7.8F, FontStyle.Regular, GraphicsUnit.Point, ((byte)(204)));
			ForeColor = Color.Black;
			FormBorderStyle = FormBorderStyle.FixedSingle;
			Icon = global::Вычислятор_Blitz.Ресурсы.Иконка;
			MaximizeBox = false;
			Name = "MainWndw";
			Opacity = 0D;
			StartPosition = FormStartPosition.CenterScreen;
			Text = "Вычислятор Blitz";
			TopMost = true;
			Група_0.ResumeLayout(false);
			Група_0.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(ИзображениеСеребра_0)).EndInit();
			((System.ComponentModel.ISupportInitialize)(ИзображениеСтрелочки_0)).EndInit();
			((System.ComponentModel.ISupportInitialize)(ИзображениеЗолота_0)).EndInit();
			Група_1.ResumeLayout(false);
			Група_1.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(ИзображениеОпыта_0)).EndInit();
			((System.ComponentModel.ISupportInitialize)(ИзображениеСтрелочки_1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(ИзображениеЗолота_1)).EndInit();
			ResumeLayout(false);
		}
	}
}